id: PF95A9F0D
initial_creation_type: ocr
source_metadata:
  volumes:
    ecec8c2d524b4c3aa64e3e994c7b0077:
      base_file: v021.txt
      image_group_id: I1PD95866
      title: དཔལ་གསང་བ་འདུས་པའི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག།
      total_pages: 1477
      volume_number: 21
